AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon ECR Repository for Wish Keeper Docker Images'

Parameters:
  RepositoryName:
    Type: String
    Default: wish-keeper
    Description: Name of the ECR repository
    AllowedPattern: '^[a-z0-9-_]+$'
    ConstraintDescription: Repository name must contain only lowercase letters, numbers, hyphens, and underscores

  ImageTagMutability:
    Type: String
    Default: MUTABLE
    AllowedValues:
      - MUTABLE
      - IMMUTABLE
    Description: Image tag mutability setting

  ScanOnPush:
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Enable automatic image scanning on push

  RetentionCount:
    Type: Number
    Default: 30
    MinValue: 1
    MaxValue: 1000
    Description: Number of images to retain

Resources:
  # ECR Repository
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      ImageTagMutability: !Ref ImageTagMutability
      ImageScanningConfiguration:
        ScanOnPush: !Ref ScanOnPush
      EncryptionConfiguration:
        EncryptionType: AES256
      LifecyclePolicy:
        LifecyclePolicyText: !Sub |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last ${RetentionCount} images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": ${RetentionCount}
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      Tags:
        - Key: Name
          Value: !Ref RepositoryName
        - Key: ManagedBy
          Value: CloudFormation

  # Repository Policy - Allow CodeBuild and ECS access
  ECRRepositoryPolicy:
    Type: AWS::ECR::RepositoryPolicy
    Properties:
      RepositoryName: !Ref ECRRepository
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
                - ecs-tasks.amazonaws.com
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload

Outputs:
  RepositoryName:
    Description: ECR Repository Name
    Value: !Ref ECRRepository
    Export:
      Name: !Sub '${AWS::StackName}-repository-name'

  RepositoryArn:
    Description: ECR Repository ARN
    Value: !GetAtt ECRRepository.Arn
    Export:
      Name: !Sub '${AWS::StackName}-repository-arn'

  RepositoryUri:
    Description: ECR Repository URI
    Value: !GetAtt ECRRepository.RepositoryUri
    Export:
      Name: !Sub '${AWS::StackName}-repository-uri'
